### ISSUE TITLE
Memoize dependencies

### ISSUE THREAD

**Issue by saml** [TakenPilot/gulp-group-concat#2]
Given an input:

``` js
{
  'a.css': ['1.css', '2.css'],  
  'b.css': ['1.css', '2.css', '4.css'],
  'c.css': ['2.css', '3.css', '4.css']
}
```

We can draw dependency graph (Makefile as an example):

``` makefile
# <target>: <prerequisites>
# `$^` are prerequisites and `$@` is target
a.css: 1.css 2.css
    cat $^ > $@
b.css: a.css 4.css
    cat $^ > $@
2+4.css: 2.css 4.css
    cat $^ > $@
c.css: 2+4.css 3.css
    cat $^ > $@
```

`a.css` (`1+2.css`)  and `2+4.css` are re-used to build b.css and c.css.

Not sure how much time this will save. Could be a lot.

I'm also assuming concatenation order does not matter. For example, `'c.css': ['2.css', '3.css', '4.css']`  is same as `'c.css': ['2.css', '4.css', '3.css']`.

If concatenation order matters... probably have to think differently.

**Comment by kgao** [comment]
there r dups,  why not b.css = a.css + 4.css

**Comment by saml** [comment]
@kgao Yah example input is bad.

Another example:

```
a = 1 + 2
b = 1 + 2 + 4
c = 2 + 3 + 4
d = 1 + 2 + 3 + 4
e = 2 + 4 + 5
```

So,

```
a = 1 + 2
b = a + 4
c' = 2 + 4
c = c' + 3
d = 1 + c
e = c' + 5
```

**Comment by ironspecs** [comment]
Concatenation order matters, because some people who wrote components did so by trial-and-error.  So their css relies on occurring in a certain order so it can "win" against other components.  @kgao @saml

**Comment by saml** [comment]
yah. in that case, i'll try to load css files in memory once and concat. assuming it re-reads source css during concatenation.

**Comment by ironspecs** [comment]
It's close to that already:  
https://github.com/TakenPilot/gulp-group-concat/blob/master/index.js#L35
https://github.com/TakenPilot/gulp-group-concat/blob/master/index.js#L54

and the plain copy is just reading from memory.  Because `gulp.src` only reads each file only once, we know that isn't the problem.

There are two things slowing down this module, I think:
- Massive memory requests during the concatenation, most of which is redundant duplication.
- A lot of "unique" disk IO from a huge area of memory.

We copy each file's data into several other files, over and over and over...  And when we do that, we're concatenating all the little pieces with each other as well, repeatedly!

**Comment by ironspecs** [comment]
Back to your first idea...  We could look for common patterns, and memoize those.  

For example, in a lot of files that are concatenated like this, the start of the files are often the same globals.

~~Also, often files within the same folder are concatenated together.~~ Except in our case.

We could use common patterns like those to create saved groupings?

**Comment by saml** [comment]
Actually, I'm not 100% convinced if concatenation is bottleneck. Looks like we also minify after concat in the project we use this. We could bypass concatenation phase all together maybe?

Probably blaming wrong module. Gonna move this to the other project.

**Comment by ironspecs** [comment]
@saml Haha, I looked into that too.  It's _definitely_ the concatenation.

**Comment by ironspecs** [comment]
~~This could be something as well.  http://stackoverflow.com/questions/13859543/fast-way-to-concatenate-strings-in-nodejs-javascript~~

~~Maybe we should try without using Buffer.~~ @saml 

~~We're currently using this: https://nodejs.org/api/buffer.html#buffer_class_method_buffer_concat_list_totallength~~

Tried it.  Made it slower.

Another option would be to investigate the through2 library, and its use of the highWatermark of 16.

**Comment by ironspecs** [comment]
I'm going to close this issue, since we can't use a dependency graph because order matters.
