### ISSUE TITLE
Preserve order

### ISSUE THREAD

**Issue by hrach** [TakenPilot/gulp-group-concat#3]
Hi, I have defined groups like:

``` js
var groups = {
        'static/assets/build/lib-plupload.min.js': [
            'static/assets/js/libs/plupload/plupload.full.js',
            'static/assets/js/libs/plupload/jquery.plupload.queue.js',
            'static/assets/js/libs-l10n/plupload.cs.js'
        ]
};
```

However, in compiled (concated) version, ploupload.cs.js is packged as first. I think this is a bug. Can I do some workaround?

**Comment by ironspecs** [comment]
Hmm, they should be in order.  I'll do some tests to see if I can reproduce what you're seeing.

Update:  Yeah, I can reproduce it, and I have a failing unit test created and everything.  I'll have a fix soon, I hope.

Update 2: I know what's happening now, and I'm debating if this is a new feature or not.  I'll make a new post for it.

**Comment by ironspecs** [comment]
Consider this failing unit test:

``` js
  it('matches are concatenated in order', function (done) {
    gulp.src('./test/fixtures/*')
      .pipe(groupConcat({
        myFile1: ['**/*2*', '**/*1*']
      }))
      .pipe(gUtil.buffer(function (err, files) {
        var contents = files[0].contents.toString();
        expect(contents.indexOf('first text')).to.be.above(contents.indexOf('second text'));
        done();
      }));
  });
```

The _reason_ that it fails is that `gulp.src('./test/fixtures/*')` reads the files in a certain order, and that order is preserved for group-concat.  This passes:

``` js
  it('matches are concatenated in order', function (done) {
    gulp.src([
      './test/fixtures/**/*2*',  //changed the order here
      './test/fixtures/**/*1*'
    ])
      .pipe(groupConcat({
        myFile1: ['**/*2*', '**/*1*']
      }))
      .pipe(gUtil.buffer(function (err, files) {
        var contents = files[0].contents.toString();
        expect(contents.indexOf('first text')).to.be.above(contents.indexOf('second text'));
        done();
      }));
  });
```

So, _re-ordering_ the files from their previous order isn't a feature yet.  It takes the files as they come, and places them into the appropriate buckets.

To get your code to work, you'll have to pass that ordering to `gulp.src`, and then you'll get the order of concatenation that you want.

Maybe something like this:

``` js
    gulp.src([
      'static/assets/js/libs/**/*.js',  //load these before the l10n
      'static/assets/js/libs-l10n/**/*.js'
    ]).pipe(groupConcat({
         'static/assets/build/lib-plupload.min.js': '**/*plupload.*js' //anything with this keyword
      }));
```

**Comment by hrach** [comment]
I see, it would be a nice feature. Currently I "fixed" it like this

``` js
js_paths = Object.keys(groups).map(function(key) { return groups[key]; });
js_paths = [].concat.apply([], js_paths);

 gulp.src(js_paths).pipe(groupConcat(gruops));
```

Thank you!
