### ISSUE TITLE
support gulp-uglify ?

### ISSUE THREAD

**Issue by goldcome** [TakenPilot/gulp-group-concat#4]
when i use gulp-uglify,not work
is it possible to be work?thanks

```
[17:11:36] Using gulpfile ~/workplace/wechat/front/gulpfile.js
[17:11:36] Starting 'concatjs'...
[17:11:36] Finished 'concatjs' after 12 ms
[17:11:36] main.js: Unexpected token: keyword (var)
```

**Comment by ironspecs** [comment]
This module just concats everything.  If your code is missing semi-colons or missing other syntax that when concatenated will cause issues, it needs to be fixed.

I don't think this module should modify code.

**Comment by goldcome** [comment]
thanks!
I have tested it,it my mistake,running like this

```
...
 .pipe(groupConcat(concatjs_json))
 .pipe(uglify())
 .pipe(gulp.dest(config.p_script));
...
```

does not work because of errors of my js files,not this module，thanks,i close this issue
